import type { MasterPlanInputs } from '../types';
import { DEFAULT_RATES, DEFAULT_ALLOCATION } from './constants';

export const defaultClientInputs = (): MasterPlanInputs => ({
  client: {
    name: 'Vikram & Ananya Sharma',
    email: 'vikram.sharma@example.com',
    advisor: 'Sound Thesis Wealth Advisory',
    reviewDate: '2026-09-01',
    notes: 'Primary focus is securing early retirement at age 45 with essential children education funded.',
  },
  currentAge: 34,
  retirementAge: 45,
  lifeExpectancy: 80,
  inflation: DEFAULT_RATES.inflation,
  annualIncome: 2500000,
  monthlyExpenditure: 100000,
  assets: [
    {
      id: 're-plots',
      name: 'Real Estate — Plots',
      value: 11200000,
      returnRate: DEFAULT_RATES.realEstateReturn,
      category: 'realestate',
      currency: 'INR',
      liquidateAtRetirement: false,
    },
    {
      id: 'gold-physical',
      name: 'Gold — Physical',
      value: 5000000,
      returnRate: DEFAULT_RATES.goldReturn,
      category: 'gold',
      currency: 'INR',
      liquidateAtRetirement: false,
    },
    {
      id: 'liquid-cash',
      name: 'Liquid — Cash',
      value: 3500000,
      returnRate: DEFAULT_RATES.liquidReturn,
      category: 'liquid',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 're-flat',
      name: 'Real Estate — Flat',
      value: 2500000,
      returnRate: DEFAULT_RATES.realEstateReturn,
      category: 'realestate',
      currency: 'INR',
      liquidateAtRetirement: false,
    },
    {
      id: 'mf-equity',
      name: 'Mutual Funds — Equity',
      value: 630000,
      returnRate: DEFAULT_RATES.equityReturn,
      category: 'equity',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 'liquid-funds',
      name: 'Liquid — Funds',
      value: 363000,
      returnRate: DEFAULT_RATES.liquidReturn,
      category: 'liquid',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 'gold-digital',
      name: 'Gold — Digital',
      value: 133000,
      returnRate: DEFAULT_RATES.goldReturn,
      category: 'gold',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
  ],
  sip: {
    amount: 90000,
    equitySplit: DEFAULT_ALLOCATION.equitySplit,
    debtSplit: DEFAULT_ALLOCATION.debtSplit,
    stepUp: 0,
    equityReturn: DEFAULT_RATES.equityReturn,
    debtReturn: DEFAULT_RATES.debtReturn,
  },
  stp: {
    active: true,
    source: 'idle-cash',
    lumpsum: 3500000,
    monthlyTransfer: 200000,
    liquidReturn: DEFAULT_RATES.liquidReturn,
    equitySplit: DEFAULT_ALLOCATION.equitySplit,
    debtSplit: DEFAULT_ALLOCATION.debtSplit,
    liquidCap: 1000000,
  },
  swp: {
    monthlyNeedToday: 150000,
    postRetirementReturn: DEFAULT_RATES.postRetirementReturn,
    taxRate: 10,
    startAge: 45,
    endAge: 80,
  },
  goals: [
    {
      id: 'goal-education',
      name: "Child's Higher Education",
      targetAmount: 5000000,
      yearsToGoal: 8,
      priority: 'essential',
      inflation: 8,
      recurring: false,
    },
    {
      id: 'goal-retirement',
      name: 'Retirement Corpus',
      targetAmount: 15000000,
      yearsToGoal: 11,
      priority: 'essential',
      inflation: 5,
      recurring: false,
    },
    {
      id: 'goal-vacation',
      name: 'International Vacation',
      targetAmount: 1500000,
      yearsToGoal: 3,
      priority: 'aspirational',
      inflation: 5,
      recurring: false,
    },
  ],
});
