import type { MasterPlanInputs } from '../types';
import { DEFAULT_RATES, DEFAULT_ALLOCATION } from './constants';

/**
 * Single source of truth for a blank planning workspace: every user-entered
 * financial default is 0/empty so a zero-data state never produces invented
 * outputs. Demo data is opt-in only via demoClientInputs().
 */
export const createEmptyPlan = (): MasterPlanInputs => ({
  client: {
    name: '',
    email: '',
    advisor: '',
    reviewDate: '',
    notes: '',
    maritalStatus: '',
    familyComposition: '',
    planningPurpose: '',
    goalsSummary: '',
    insuranceSummary: '',
    investmentPhilosophy: '',
    adviceRequested: '',
    familyMembers: [],
    incomeSources: [],
    insurancePolicies: [],
  },
  currentAge: 0,
  retirementAge: 0,
  lifeExpectancy: 0,
  inflation: 0,
  annualIncome: 0,
  monthlyLivingExpenses: 0,
  monthlyExpenditure: 0,
  assets: [],
  liabilities: [],
  sip: {
    amount: 0,
    equitySplit: 0,
    debtSplit: 0,
    stepUp: 0,
    equityReturn: 0,
    debtReturn: 0,
  },
  stp: {
    active: false,
    source: 'idle-cash',
    lumpsum: 0,
    monthlyTransfer: 0,
    liquidReturn: 0,
    equitySplit: 0,
    debtSplit: 0,
    liquidCap: 0,
  },
  swp: {
    monthlyNeedToday: 0,
    postRetirementReturn: 0,
    taxRate: 0,
    startAge: 0,
    endAge: 0,
  },
  goals: [],
});

export const defaultClientInputs = createEmptyPlan;

export const demoClientInputs = (): MasterPlanInputs => ({
  client: {
    name: 'Vikram & Ananya Sharma',
    email: 'vikram.sharma@example.com',
    advisor: 'Sound Thesis Wealth Advisory',
    reviewDate: '2026-09-01',
    notes: 'Primary focus is securing early retirement at age 45 with essential children education funded.',
    maritalStatus: 'Married',
    familyComposition: 'Two children; education funding is a priority.',
    planningPurpose: 'Build retirement security while funding family milestones.',
    goalsSummary: 'Early retirement and children’s education.',
    insuranceSummary: 'Review life and health cover alongside the investment plan.',
    investmentPhilosophy: 'Diversified, long-term, and disciplined.',
    adviceRequested: 'Confirm the allocation and sequence the next actions.',
    familyMembers: [
      { id: 'demo-son', name: 'Child 1', relationship: 'Son', dateOfBirth: '', status: 'Education', goal: 'Higher education and early career capital' },
      { id: 'demo-daughter', name: 'Child 2', relationship: 'Daughter', dateOfBirth: '', status: 'Education', goal: 'Master’s education abroad' },
    ],
    incomeSources: [
      { id: 'demo-income-1', name: 'Primary income', amount: 0, amountInBaseCurrency: 0, currency: 'INR', frequency: 'monthly', notes: '' },
      { id: 'demo-income-2', name: 'Rental income', amount: 0, amountInBaseCurrency: 0, currency: 'INR', frequency: 'monthly', notes: '' },
    ],
    insurancePolicies: [
      { id: 'demo-life-cover', type: 'Life', provider: '', coverage: '', premium: 0, premiumFrequency: 'annual', notes: '' },
      { id: 'demo-health-cover', type: 'Health', provider: '', coverage: '', premium: 0, premiumFrequency: 'annual', notes: '' },
    ],
  },
  currentAge: 34,
  retirementAge: 45,
  lifeExpectancy: 80,
  inflation: DEFAULT_RATES.inflation,
  annualIncome: 2500000,
  monthlyLivingExpenses: 100000,
  monthlyExpenditure: 100000,
  assets: [
    {
      id: 're-plots',
      name: 'Real Estate — Plots',
      value: 11200000,
      returnRate: DEFAULT_RATES.realEstateReturn,
      category: 'realestate',
      currency: 'INR',
      liquidateAtRetirement: false,
    },
    {
      id: 'gold-physical',
      name: 'Commodities — Physical Gold',
      value: 5000000,
      returnRate: DEFAULT_RATES.goldReturn,
      category: 'gold',
      currency: 'INR',
      liquidateAtRetirement: false,
    },
    {
      id: 'liquid-cash',
      name: 'Liquid — Cash',
      value: 3500000,
      returnRate: DEFAULT_RATES.liquidReturn,
      category: 'liquid',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 're-flat',
      name: 'Real Estate — Flat',
      value: 2500000,
      returnRate: DEFAULT_RATES.realEstateReturn,
      category: 'realestate',
      currency: 'INR',
      liquidateAtRetirement: false,
    },
    {
      id: 'mf-equity',
      name: 'Mutual Funds — Equity',
      value: 630000,
      returnRate: DEFAULT_RATES.equityReturn,
      category: 'equity',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 'liquid-funds',
      name: 'Liquid — Funds',
      value: 363000,
      returnRate: DEFAULT_RATES.liquidReturn,
      category: 'liquid',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 'gold-digital',
      name: 'Commodities — Digital Gold',
      value: 133000,
      returnRate: DEFAULT_RATES.goldReturn,
      category: 'gold',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
  ],
  liabilities: [],
  sip: {
    amount: 90000,
    equitySplit: DEFAULT_ALLOCATION.equitySplit,
    debtSplit: DEFAULT_ALLOCATION.debtSplit,
    stepUp: 0,
    equityReturn: DEFAULT_RATES.equityReturn,
    debtReturn: DEFAULT_RATES.debtReturn,
  },
  stp: {
    active: true,
    source: 'idle-cash',
    lumpsum: 3500000,
    monthlyTransfer: 200000,
    liquidReturn: DEFAULT_RATES.liquidReturn,
    equitySplit: DEFAULT_ALLOCATION.equitySplit,
    debtSplit: DEFAULT_ALLOCATION.debtSplit,
    liquidCap: 1000000,
  },
  swp: {
    monthlyNeedToday: 150000,
    postRetirementReturn: DEFAULT_RATES.postRetirementReturn,
    taxRate: 10,
    startAge: 45,
    endAge: 80,
  },
  goals: [
    {
      id: 'goal-education',
      name: "Child's Higher Education",
      targetAmount: 5000000,
      yearsToGoal: 8,
      priority: 'essential',
      inflation: 8,
      recurring: false,
    },
    {
      id: 'goal-retirement',
      name: 'Retirement Corpus',
      targetAmount: 15000000,
      yearsToGoal: 11,
      priority: 'essential',
      inflation: 5,
      recurring: false,
    },
    {
      id: 'goal-vacation',
      name: 'International Vacation',
      targetAmount: 1500000,
      yearsToGoal: 3,
      priority: 'aspirational',
      inflation: 5,
      recurring: false,
    },
  ],
});
