import type { MasterPlanInputs } from '../types';
import { DEFAULT_RATES } from './constants';

/**
 * Single source of truth for a blank planning workspace: every user-entered
 * financial default is 0/empty so a zero-data state never produces invented
 * outputs. Demo data is opt-in only via demoClientInputs().
 */
export const createEmptyPlan = (): MasterPlanInputs => ({
  client: {
    name: '',
    email: '',
    advisor: '',
    reviewDate: '',
    notes: '',
    maritalStatus: '',
    familyComposition: '',
    planningPurpose: '',
    goalsSummary: '',
    insuranceSummary: '',
    investmentPhilosophy: '',
    adviceRequested: '',
    familyMembers: [],
    incomeSources: [],
    insurancePolicies: [],
  },
  currentAge: 0,
  retirementAge: 0,
  lifeExpectancy: 0,
  inflation: 0,
  annualIncome: 0,
  monthlyLivingExpenses: 0,
  monthlyExpenditure: 0,
  assets: [],
  liabilities: [],
  sip: {
    amount: 0,
    equitySplit: 0,
    debtSplit: 0,
    stepUp: 0,
    equityReturn: 0,
    debtReturn: 0,
  },
  stp: {
    active: false,
    source: 'idle-cash',
    lumpsum: 0,
    monthlyTransfer: 0,
    liquidReturn: 0,
    equitySplit: 0,
    debtSplit: 0,
    liquidCap: 0,
  },
  swp: {
    monthlyNeedToday: 0,
    postRetirementReturn: 0,
    taxRate: 0,
    startAge: 0,
    endAge: 0,
  },
  goals: [],
});

export const defaultClientInputs = createEmptyPlan;

export const demoClientInputs = (): MasterPlanInputs => ({
  client: {
    name: 'John Doe',
    email: 'john.doe@example.com',
    advisor: 'Sound Thesis Wealth Advisory',
    reviewDate: '2026-09-12',
    notes: 'Primary focus is securing early retirement at age 50 with essential children education funded. Wants to explore aggressive equity growth.',
    maritalStatus: 'Married',
    familyComposition: 'Spouse and two children; education funding is a priority.',
    planningPurpose: 'Build retirement security while funding family milestones and leaving a legacy.',
    goalsSummary: 'Early retirement, children’s education, and buying a second home in the mountains.',
    insuranceSummary: 'Needs review of life and health cover alongside the investment plan.',
    investmentPhilosophy: 'Aggressive growth with a focus on tech equities and real estate.',
    adviceRequested: 'Confirm the allocation, sequence the next actions, and optimize tax strategy.',
    familyMembers: [
      { id: 'demo-spouse', name: 'Jane Doe', relationship: 'Spouse', dateOfBirth: '1992-05-14', status: 'Working', goal: 'Joint retirement planning' },
      { id: 'demo-son', name: 'Jimmy Doe', relationship: 'Son', dateOfBirth: '2016-08-20', status: 'Education', goal: 'Higher education and early career capital' },
      { id: 'demo-daughter', name: 'Jenny Doe', relationship: 'Daughter', dateOfBirth: '2019-11-03', status: 'Education', goal: 'Master’s education abroad' },
    ],
    incomeSources: [
      { id: 'demo-income-1', name: 'Primary Salary (Tech Exec)', amount: 4500000, amountInBaseCurrency: 4500000, currency: 'INR', frequency: 'annual', notes: 'Includes bonuses' },
      { id: 'demo-income-2', name: 'Rental Income', amount: 50000, amountInBaseCurrency: 50000, currency: 'INR', frequency: 'monthly', notes: 'From downtown apartment' },
      { id: 'demo-income-3', name: 'Dividend Yields', amount: 120000, amountInBaseCurrency: 120000, currency: 'INR', frequency: 'annual', notes: 'Stock portfolio dividends' },
    ],
    insurancePolicies: [
      { id: 'demo-life-cover', type: 'Life', provider: 'Global Life Insurance', coverage: '50000000', premium: 45000, premiumFrequency: 'annual', notes: 'Term life cover' },
      { id: 'demo-health-cover', type: 'Health', provider: 'Care Health', coverage: '10000000', premium: 35000, premiumFrequency: 'annual', notes: 'Family floater' },
    ],
  },
  currentAge: 38,
  retirementAge: 50,
  lifeExpectancy: 85,
  inflation: DEFAULT_RATES.inflation,
  annualIncome: 5220000, // 4.5M + 600k rental + 120k dividends
  monthlyLivingExpenses: 150000,
  monthlyExpenditure: 150000,
  assets: [
    {
      id: 're-primary',
      name: 'Primary Residence (Villa)',
      value: 25000000,
      returnRate: DEFAULT_RATES.realEstateReturn,
      category: 'realestate',
      currency: 'INR',
      liquidateAtRetirement: false,
    },
    {
      id: 're-rental',
      name: 'Downtown Apartment',
      value: 12000000,
      returnRate: DEFAULT_RATES.realEstateReturn,
      category: 'realestate',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 'mf-equity',
      name: 'Large Cap Mutual Funds',
      value: 8500000,
      returnRate: 12.5,
      category: 'equity',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 'direct-equity',
      name: 'Tech Stocks Portfolio',
      value: 4200000,
      returnRate: 15.0,
      category: 'equity',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 'pf-debt',
      name: 'Provident Fund (EPF/PPF)',
      value: 3800000,
      returnRate: 8.1,
      category: 'debt',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
    {
      id: 'gold-physical',
      name: 'Physical Gold & Jewelry',
      value: 1500000,
      returnRate: DEFAULT_RATES.goldReturn,
      category: 'gold',
      currency: 'INR',
      liquidateAtRetirement: false,
    },
    {
      id: 'liquid-cash',
      name: 'Emergency Savings (Bank)',
      value: 1200000,
      returnRate: 4.5,
      category: 'liquid',
      currency: 'INR',
      liquidateAtRetirement: true,
    },
  ],
  liabilities: [
    {
      id: 'loan-home',
      name: 'Home Loan (Villa)',
      principal: 8500000,
      rate: 8.5,
      tenureYears: 15,
      monthlyPayment: 83700,
      includeInExpenses: true,
    },
    {
      id: 'loan-car',
      name: 'Auto Loan (SUV)',
      principal: 1200000,
      rate: 9.2,
      tenureYears: 4,
      monthlyPayment: 29900,
      includeInExpenses: true,
    }
  ],
  sip: {
    amount: 150000,
    equitySplit: 75,
    debtSplit: 25,
    stepUp: 10,
    equityReturn: 12,
    debtReturn: 7,
  },
  stp: {
    active: true,
    source: 'idle-cash',
    lumpsum: 1200000,
    monthlyTransfer: 100000,
    liquidReturn: 4.5,
    equitySplit: 80,
    debtSplit: 20,
    liquidCap: 300000,
  },
  swp: {
    monthlyNeedToday: 200000,
    postRetirementReturn: 8.5,
    taxRate: 10,
    startAge: 50,
    endAge: 85,
  },
  goals: [
    {
      id: 'goal-education-1',
      name: "Jimmy's Higher Education",
      targetAmount: 8000000,
      yearsToGoal: 8,
      priority: 'essential',
      inflation: 10,
      recurring: false,
    },
    {
      id: 'goal-education-2',
      name: "Jenny's Ivy League Education",
      targetAmount: 12000000,
      yearsToGoal: 11,
      priority: 'important',
      inflation: 10,
      recurring: false,
    },
    {
      id: 'goal-retirement',
      name: 'Retirement Corpus',
      targetAmount: 50000000,
      yearsToGoal: 12,
      priority: 'essential',
      inflation: 6,
      recurring: false,
    },
    {
      id: 'goal-vacation',
      name: 'Annual Luxury Vacations',
      targetAmount: 1500000,
      yearsToGoal: 1,
      priority: 'aspirational',
      inflation: 5,
      recurring: true,
    },
    {
      id: 'goal-mountain-home',
      name: 'Mountain Retreat Home',
      targetAmount: 25000000,
      yearsToGoal: 15,
      priority: 'aspirational',
      inflation: 6,
      recurring: false,
    }
  ],
});
