import { readFileSync } from 'fs';
import { resolve } from 'path';
import { execSync } from 'child_process';

/**
 * Vercel serverless function that serves the bundled historical market data.
 * Reads from public/data/market-data.json (generated by scripts/fetch_angel_historical.py).
 *
 * Query params:
 *   symbols - comma-separated list of symbols to return (optional)
 *   from    - start date YYYY-MM-DD (optional)
 *   to      - end date YYYY-MM-DD (optional)
 *
 * POST /api/market-data/refresh
 *   Refreshes the bundle by running the Python fetcher. Requires ADMIN_SECRET
 *   header to prevent abuse.
 */
export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, POST, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type, Authorization');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  if (req.method === 'POST') {
    return handleRefresh(req, res);
  }

  return serveBundle(req, res);
}

function serveBundle(req, res) {
  try {
    const filePath = resolve(process.cwd(), 'public', 'data', 'market-data.json');
    const raw = readFileSync(filePath, 'utf8');
    const data = JSON.parse(raw);

    const { symbols, from, to } = req.query;

    let result = data;

    if (symbols) {
      const wanted = symbols.split(',').map((s) => s.trim().toUpperCase());
      const indices = wanted
        .map((sym) => data.symbols.indexOf(sym))
        .filter((idx) => idx >= 0);

      if (indices.length === 0) {
        return res.status(400).json({ error: 'No valid symbols requested' });
      }

      const filteredPrices = indices.map((idx) => data.prices[idx]);
      const filteredInstruments = indices.map((idx) => data.instruments[idx]);
      const filteredSymbols = indices.map((idx) => data.symbols[idx]);
      const filteredStats = indices.map((idx) => data.stats[idx]);

      result = {
        ...data,
        symbols: filteredSymbols,
        instruments: filteredInstruments,
        prices: filteredPrices,
        stats: filteredStats,
        covariance: [],
        correlation: [],
      };
    }

    if (from || to) {
      const startDate = from || '2000-01-01';
      const endDate = to || new Date().toISOString().split('T')[0];
      result = filterByDateRange(result, startDate, endDate);
    }

    return res.status(200).json(result);
  } catch (err) {
    console.error('Market data API error:', err);
    return res.status(500).json({
      error: 'Market data bundle not found. Run `npm run fetch:data` first.',
    });
  }
}

function filterByDateRange(data, startDate, endDate) {
  if (!data.prices || data.prices.length === 0) return data;

  const slicePrices = data.prices.map((series) => {
    const dates = series.dates;
    const startIdx = dates.findIndex((d) => d >= startDate);
    const endIdx = dates.findIndex((d) => d > endDate);
    const start = startIdx >= 0 ? startIdx : 0;
    const end = endIdx >= 0 ? endIdx : dates.length;
    if (start >= end) {
      return { ...series, dates: [], closes: [] };
    }
    return {
      ...series,
      dates: dates.slice(start, end),
      closes: series.closes.slice(start, end),
    };
  });

  const validPrices = slicePrices.filter((p) => p.dates.length > 0);
  const dateRange = validPrices.length > 0
    ? { from: validPrices[0].dates[0], to: validPrices[0].dates[validPrices[0].dates.length - 1] }
    : data.dateRange;

  return {
    ...data,
    prices: slicePrices,
    dateRange,
  };
}

function handleRefresh(req, res) {
  const adminSecret = process.env.ADMIN_SECRET;
  const provided = req.headers['authorization']?.replace('Bearer ', '') || req.body?.secret;

  if (adminSecret && provided !== adminSecret) {
    return res.status(401).json({ error: 'Unauthorized' });
  }

  try {
    const cwd = resolve(process.cwd());
    const python = resolve(cwd, '.venv', 'bin', 'python');
    const script = resolve(cwd, 'scripts', 'fetch_angel_historical.py');
    const output = execSync(`"${python}" "${script}"`, { cwd, encoding: 'utf8', timeout: 300000 });
    return res.status(200).json({ success: true, output: output.split('\n').filter(Boolean) });
  } catch (err) {
    console.error('Market data refresh error:', err);
    return res.status(500).json({
      error: 'Failed to refresh market data',
      detail: err?.stderr || err?.message,
    });
  }
}
