import { readFileSync } from 'fs';
import { resolve } from 'path';

/**
 * Vercel serverless function that serves the bundled historical market data.
 * Reads from public/data/market-data.json (generated by scripts/fetch_historical.py).
 *
 * Query params:
 *   symbols - comma-separated list of symbols to return (optional)
 *   from    - start date YYYY-MM-DD (optional)
 *   to      - end date YYYY-MM-DD (optional)
 */
export default function handler(req, res) {
  res.setHeader('Access-Control-Allow-Origin', '*');
  res.setHeader('Access-Control-Allow-Methods', 'GET, OPTIONS');
  res.setHeader('Access-Control-Allow-Headers', 'Content-Type');

  if (req.method === 'OPTIONS') {
    return res.status(200).end();
  }

  try {
    const filePath = resolve(process.cwd(), 'public', 'data', 'market-data.json');
    const raw = readFileSync(filePath, 'utf8');
    const data = JSON.parse(raw);

    const { symbols, from, to } = req.query;

    let result = data;

    if (symbols) {
      const wanted = symbols.split(',').map((s) => s.trim().toUpperCase());
      const indices = wanted
        .map((sym) => data.symbols.indexOf(sym))
        .filter((idx) => idx >= 0);

      if (indices.length === 0) {
        return res.status(400).json({ error: 'No valid symbols requested' });
      }

      const filteredPrices = indices.map((idx) => data.prices[idx]);
      const filteredInstruments = indices.map((idx) => data.instruments[idx]);
      const filteredSymbols = indices.map((idx) => data.symbols[idx]);
      const filteredStats = indices.map((idx) => data.stats[idx]);

      const filterMatrix = (matrix) => indices.map((i) => indices.map((j) => matrix[i][j]));

      result = {
        ...data,
        symbols: filteredSymbols,
        instruments: filteredInstruments,
        prices: filteredPrices,
        stats: filteredStats,
        covariance: filterMatrix(data.covariance),
        correlation: filterMatrix(data.correlation),
        returnsMatrix: indices.map((i) => data.returnsMatrix[i]),
      };
    }

    if (from || to) {
      const startDate = from || result.dateRange.from;
      const endDate = to || result.dateRange.to;
      result = filterByDateRange(result, startDate, endDate);
    }

    return res.status(200).json(result);
  } catch (err) {
    console.error('Market data API error:', err);
    return res.status(500).json({
      error: 'Market data bundle not found. Run `python scripts/fetch_historical.py` first.',
    });
  }
}

function filterByDateRange(data, startDate, endDate) {
  if (!data.prices || data.prices.length === 0) return data;

  const dates = data.prices[0].dates;
  const startIdx = dates.findIndex((d) => d >= startDate);
  const endIdx = dates.findIndex((d) => d > endDate);
  const start = startIdx >= 0 ? startIdx : 0;
  const end = endIdx >= 0 ? endIdx : dates.length;

  if (start >= end) return data;

  const sliceDates = dates.slice(start, end);
  const slicePrices = data.prices.map((series) => ({
    ...series,
    dates: sliceDates,
    closes: series.closes.slice(start, end),
  }));

  return {
    ...data,
    prices: slicePrices,
    dateRange: { from: sliceDates[0], to: sliceDates[sliceDates.length - 1] },
  };
}
